<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../SharedProjectConfiguration.props" />

  <PropertyGroup>
    <RootNamespace>Software9119.Collection.Superb</RootNamespace>
    <AssemblyName>Software9119.Collection.Superb</AssemblyName>
    <PackageOutputFolder>./../packages/</PackageOutputFolder>
  </PropertyGroup>

  <PropertyGroup Label="Package">
    <PackageVersion>3.1.0</PackageVersion>
    <PackageReadmeFile>./README.md</PackageReadmeFile>
    <Description>.NET collections enhancements going further and beyond.</Description>
    <PackageTags>Collection,Collections</PackageTags>
    <PackageProjectUrl>https://github.com/deep-outcome/Software9119.Collection.Superb</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup Label="Info">
    <None Include="./../LICENSE.md" Pack="true" PackagePath="\" />
    <None Include="./README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PackageId>$(AssemblyName).$(Configuration)</PackageId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PackageId>$(AssemblyName)</PackageId>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <Target Name="CopyPackage" AfterTargets="Pack">
    <Copy SourceFiles="$(OutputPath)..\$(PackageId).$(PackageVersion).nupkg" DestinationFolder="$(PackageOutputFolder)" />
    <Copy SourceFiles="$(OutputPath)..\$(PackageId).$(PackageVersion).snupkg" DestinationFolder="$(PackageOutputFolder)" />
  </Target>

  <ItemGroup>
    <None Include="./.editorconfig" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400" PrivateAssets="All" />
    <PackageReference Include="Software9119.ProxyNsAnalyzer" Version="1.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
